Enhance command replacer
- Use functions for easier reasoning about the code.
- Compare commands to an allow list; easier to read and scalable.
- Check for unsafe tokens.
- Add default options so we don't have to repeat them in every COMMAND-OUTPUT.
- Replace eval with ${EXECUTABLE_COMMAND[@]} to prevent injections.

Example errors:

`ls -l`
ERROR: refusing to run arbitrary command: ls

`phpcs && ls -l`
ERROR: refusing unsafe token: &&